'use strict';
// Generates src/index.mjs — a thin ESM facade over the CommonJS entry
// (src/index.js) so the package can be consumed with either `require()` or
// `import`. The facade re-exports every named binding plus a default export.
//
// Re-run whenever src/index.js's export set changes:
//   node tools/gen-esm.js
//
// It introspects the actual CJS module rather than parsing the source, so the
// ESM surface can never drift from what require() sees. `prepublishOnly` runs it.

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const mod = require(path.join(ROOT, 'src/index.js'));

// Only keys that are valid JS identifiers can be named ESM exports.
const names = Object.keys(mod).filter((k) => /^[A-Za-z_$][\w$]*$/.test(k));
const skipped = Object.keys(mod).filter((k) => !/^[A-Za-z_$][\w$]*$/.test(k));
if (skipped.length) {
  console.warn('gen-esm: skipping non-identifier export keys:', skipped.join(', '));
}

const out =
`// AUTO-GENERATED by tools/gen-esm.js — do not edit.
// ESM facade over the CommonJS entry (src/index.js). Import named bindings
// (\`import { leadLag } from 'ringdater-js'\`) or the whole namespace as default
// (\`import RD from 'ringdater-js'\`).
import RD from './index.js';

export default RD;

export const {
${names.map((n) => '  ' + n).join(',\n')},
} = RD;
`;

fs.writeFileSync(path.join(ROOT, 'src/index.mjs'), out);
console.log('gen-esm: wrote src/index.mjs with', names.length, 'named exports');
