'use strict';
// Stamp the package.json version everywhere it must agree:
//   src/version.js   — the library's RD.VERSION (bundled into web/ringdater.bundle.js)
//   web/index.html   — the header badge + cache-busting ?v= on every local asset,
//                      so browsers pick up new bundles without a hard refresh.
// package.json is the SINGLE SOURCE OF TRUTH. Run via `npm run stamp`; the npm
// `version` lifecycle script wires this into `npm version patch|minor|major`
// (bump -> stamp -> rebuild esm+bundle -> test -> commit + tag).
// test/version_test.js fails the suite whenever any copy drifts.

const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const version = require(path.join(ROOT, 'package.json')).version;

fs.writeFileSync(path.join(ROOT, 'src', 'version.js'),
  "'use strict';\n" +
  '// GENERATED by tools/stamp-version.js from package.json — do not edit by hand.\n' +
  "module.exports = { VERSION: '" + version + "' };\n");

const htmlPath = path.join(ROOT, 'web', 'index.html');
let html = fs.readFileSync(htmlPath, 'utf8');
html = html.replace(/(href|src)="\.\/([A-Za-z0-9_.-]+)(\?v=[^"]*)?"/g,
  '$1="./$2?v=' + version + '"');
html = html.replace(/<span class="ver">[^<]*<\/span>/,
  '<span class="ver">v' + version + '</span>');
fs.writeFileSync(htmlPath, html);

console.log('stamped v' + version + ' -> src/version.js, web/index.html');
